language: php
php:
  - 5.3
  - 5.4
before_script:
  - pear install --alldeps pear/PHP_CodeSniffer
  - pear install --alldeps phpunit/PHP_Invoker
  - pear install --alldeps phpunit/DbUnit
  - pear install --alldeps phpunit/PHPUnit_Selenium
  - pear install --alldeps phpunit/PHPUnit_Story
  - phpenv rehash
script: phpunit
